import { upsertFile, createPR, createBranch } from '../github/client.js';
import { runClaudeCodeAgent } from './claude-code-agent.js';

// Files that must go through a PR — never direct push to main
const CORE_FILES = new Set([
  'src/brain.ts',
  'src/discord/handlers.ts',
  'src/index.ts',
  'src/tools/builder.ts',
  'src/memory/supabase.ts',
  'src/overnight/trainer.ts',
  'src/tools/registry.ts',
  'src/discord/channels.ts',
]);

export interface SelfModifyPlan {
  files: Array<{ path: string; content: string }>;
  npmPackage?: string;
  envVarName?: string;
  reviewNotes: string;
  isCoreChange: boolean;
  prBranch?: string;
}

export interface SelfModifyResult {
  success: boolean;
  message: string;
  plan?: SelfModifyPlan;
}

async function generateAndReviewCode(intent: string): Promise<SelfModifyPlan> {
  const result = await runClaudeCodeAgent(intent);

  if (!result.success || result.files.length === 0) {
    throw new Error(result.reviewNotes);
  }

  const isCoreChange = result.files.some(f => CORE_FILES.has(f.path));

  return {
    files: result.files,
    npmPackage: undefined,  // Claude Code handles package.json directly
    envVarName: undefined,
    reviewNotes: result.reviewNotes,
    isCoreChange,
    ...(isCoreChange ? { prBranch: `self-modify/${Date.now()}` } : {}),
  };
}

/**
 * Generate code for an intent and return a proposal for Jake to approve.
 * Does NOT push anything yet — caller stores the plan and waits for approval.
 */
export async function requestSelfModify(intent: string): Promise<SelfModifyResult> {
  try {
    console.log(`[self-modify] Generating code for: ${intent}`);
    const plan = await generateAndReviewCode(intent);

    const fileList = plan.files.map(f => `\`${f.path}\``).join(', ');
    const pkgNote = plan.npmPackage ? ` + add \`${plan.npmPackage}\` to package.json` : '';
    const envNote = plan.envVarName
      ? ` You'll need to add \`${plan.envVarName}\` to Railway env vars to activate it.`
      : '';

    let message: string;
    if (plan.isCoreChange) {
      message =
        `This requires editing core files. Claude Code reviewed it — ${plan.reviewNotes}.\n\n` +
        `Files: ${fileList}${pkgNote}.${envNote}\n\n` +
        `Say **ship it** and I'll open a PR — Railway redeploys on merge.`;
    } else {
      message =
        `I'll create ${fileList}${pkgNote}. Claude Code reviewed it — ${plan.reviewNotes}.${envNote}\n\n` +
        `Want me to ship it? (yes/no)`;
    }

    return { success: true, message, plan };
  } catch (err) {
    console.error('[self-modify] Failed:', err);
    return { success: false, message: `Failed to generate code: ${(err as Error).message}` };
  }
}

/**
 * Execute an approved SelfModifyPlan — push files to GitHub.
 * Safe changes push directly to main. Core changes open a PR on a branch.
 */
export async function executeSelfModifyPlan(
  plan: SelfModifyPlan
): Promise<{ success: boolean; message: string; prUrl?: string }> {
  try {
    if (plan.isCoreChange && plan.prBranch) {
      // Create branch from main
      await createBranch('jarvis', plan.prBranch);

      // Push all files to the branch
      for (const file of plan.files) {
        console.log(`[self-modify] Pushing ${file.path} to branch ${plan.prBranch}`);
        await upsertFile(
          'jarvis',
          file.path,
          file.content,
          `feat: ${plan.prBranch}`,
          plan.prBranch
        );
      }

      if (plan.npmPackage) {
        await addNpmDependency(plan.npmPackage, plan.prBranch);
      }

      const prUrl = await createPR(
        'jarvis',
        `feat: ${plan.prBranch.replace('self-modify/', 'auto-')}`,
        `Auto-generated by Jarvis self-modification pipeline.\n\nOpus review: ${plan.reviewNotes}`,
        plan.prBranch,
        'main'
      );

      const envNote = plan.envVarName
        ? ` Add \`${plan.envVarName}\` to Railway env vars after merging.`
        : '';
      return {
        success: true,
        message: `PR opened: ${prUrl}${envNote} Railway redeploys automatically on merge.`,
        prUrl,
      };
    } else {
      // Safe change — push directly to main
      for (const file of plan.files) {
        console.log(`[self-modify] Pushing ${file.path} to main`);
        await upsertFile(
          'jarvis',
          file.path,
          file.content,
          `feat: auto-install ${file.path}`
        );
      }

      if (plan.npmPackage) {
        await addNpmDependency(plan.npmPackage);
      }

      const envNote = plan.envVarName
        ? ` Add \`${plan.envVarName}\` to Railway env vars to activate it.`
        : '';
      return {
        success: true,
        message: `Pushed ${plan.files.length} file(s) to GitHub. Railway is rebuilding (~2 min).${envNote}`,
      };
    }
  } catch (err) {
    return { success: false, message: `Execution failed: ${(err as Error).message}` };
  }
}

async function addNpmDependency(packageName: string, branch?: string): Promise<void> {
  const { getFileContent } = await import('../github/client.js');
  const raw = await getFileContent('jarvis', 'package.json');
  if (!raw) throw new Error('package.json not found in jarvis repo');

  const pkg = JSON.parse(raw);
  pkg.dependencies[packageName] = 'latest';

  await upsertFile(
    'jarvis',
    'package.json',
    JSON.stringify(pkg, null, 2) + '\n',
    `feat: add ${packageName} dependency`,
    branch
  );
}
