import { upsertFile, createPR, createBranch } from '../github/client.js';
import { runClaudeCodeAgent, NotifyFn } from './claude-code-agent.js';

// Files that must go through a PR — never direct push to main
const CORE_FILES = new Set([
  'src/brain.ts',
  'src/discord/handlers.ts',
  'src/index.ts',
  'src/tools/builder.ts',
  'src/memory/supabase.ts',
  'src/overnight/trainer.ts',
  'src/tools/registry.ts',
  'src/discord/channels.ts',
]);

export interface SelfModifyPlan {
  files: Array<{ path: string; content: string }>;
  npmPackage?: string;
  envVarName?: string;
  reviewNotes: string;
  isCoreChange: boolean;
  prBranch?: string;
}

export interface SelfModifyResult {
  success: boolean;
  message: string;
  plan?: SelfModifyPlan;
}

async function generateAndReviewCode(intent: string, notify?: NotifyFn): Promise<SelfModifyPlan> {
  const result = await runClaudeCodeAgent(intent, notify);

  if (!result.success || result.files.length === 0) {
    throw new Error(result.reviewNotes);
  }

  const isCoreChange = result.files.some(f => CORE_FILES.has(f.path));

  return {
    files: result.files,
    npmPackage: undefined,  // Claude Code handles package.json directly
    envVarName: undefined,
    reviewNotes: result.reviewNotes,
    isCoreChange,
    prBranch: `self-modify/${Date.now()}`,  // always branch — Jake reviews before merge
  };
}

/**
 * Generate code for an intent and return a proposal for Jake to approve.
 * Does NOT push anything yet — caller stores the plan and waits for approval.
 */
export async function requestSelfModify(intent: string, notify?: NotifyFn): Promise<SelfModifyResult> {
  try {
    console.log(`[self-modify] Generating code for: ${intent}`);
    const plan = await generateAndReviewCode(intent, notify);

    const fileList = plan.files.map(f => `\`${f.path}\``).join(', ');
    const pkgNote = plan.npmPackage ? ` + add \`${plan.npmPackage}\` to package.json` : '';
    const envNote = plan.envVarName
      ? ` You'll need to add \`${plan.envVarName}\` to Railway env vars to activate it.`
      : '';

    const coreNote = plan.isCoreChange ? ' (touches core files)' : '';
    const message =
      `Done${coreNote}. Claude Code reviewed it — ${plan.reviewNotes}.\n\n` +
      `Files: ${fileList}${pkgNote}.${envNote}\n\n` +
      `Say **ship it** and I'll open a PR for your review. Railway only redeploys when you merge.`;

    return { success: true, message, plan };
  } catch (err) {
    console.error('[self-modify] Failed:', err);
    return { success: false, message: `Failed to generate code: ${(err as Error).message}` };
  }
}

/**
 * Execute an approved SelfModifyPlan — always opens a PR on a branch.
 * Jake reviews and merges manually. Railway only redeploys on merge to main.
 */
export async function executeSelfModifyPlan(
  plan: SelfModifyPlan
): Promise<{ success: boolean; message: string; prUrl?: string }> {
  try {
    const branch = plan.prBranch!;

    await createBranch('jarvis', branch);

    for (const file of plan.files) {
      console.log(`[self-modify] Pushing ${file.path} to branch ${branch}`);
      await upsertFile('jarvis', file.path, file.content, `feat: ${branch}`, branch);
    }

    if (plan.npmPackage) {
      await addNpmDependency(plan.npmPackage, branch);
    }

    const prUrl = await createPR(
      'jarvis',
      `feat: ${branch.replace('self-modify/', 'auto-')}`,
      `Auto-generated by Jarvis self-modification pipeline.\n\nClaude Code review: ${plan.reviewNotes}`,
      branch,
      'main'
    );

    const envNote = plan.envVarName
      ? ` Add \`${plan.envVarName}\` to Railway env vars after merging.`
      : '';
    return {
      success: true,
      message: `PR opened: ${prUrl}${envNote} Railway redeploys when you merge.`,
      prUrl,
    };
  } catch (err) {
    return { success: false, message: `Execution failed: ${(err as Error).message}` };
  }
}

async function addNpmDependency(packageName: string, branch?: string): Promise<void> {
  const { getFileContent } = await import('../github/client.js');
  const raw = await getFileContent('jarvis', 'package.json');
  if (!raw) throw new Error('package.json not found in jarvis repo');

  const pkg = JSON.parse(raw);
  pkg.dependencies[packageName] = 'latest';

  await upsertFile(
    'jarvis',
    'package.json',
    JSON.stringify(pkg, null, 2) + '\n',
    `feat: add ${packageName} dependency`,
    branch
  );
}
